select * from asiacup;
select * from batsman_data_odi;
select * from batsman_data_t20i;
select * from bowler_data_odi;
select * from bowler_data_t20i;
select * from wicketkeeper_data_odi;
select * from wicketkeeper_data_t20i;
select * from champion;


--------------------------------------------CREATE-TABLE--------------------------------------------



CREATE TABLE asiacup (
    id                          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    team                        VARCHAR2(50) NOT NULL,
    opponent                    VARCHAR2(50) NOT NULL,
    format                      VARCHAR2(10) CHECK (format IN ('ODI', 'T20I')),
    ground                      VARCHAR2(100),
    year                        NUMBER(4),
    toss                        VARCHAR2(10),
    selection                   VARCHAR2(20),
    run_scored                  NUMBER(5,2),
    wicket_lost                 NUMBER(3),
    fours                       NUMBER(3),
    sixes                       NUMBER(3),
    extras                      NUMBER(4,2),
    run_rate                    NUMBER(4,2),
    avg_bat_strike_rate         NUMBER(5,2),
    highest_score               NUMBER(5),
    wicket_taken                NUMBER(3),
    given_extras                NUMBER(3),
    highest_individual_wicket   NUMBER(3),
    player_of_the_match         VARCHAR2(100),
    result                      VARCHAR2(20) CHECK (result IN ('Won', 'Lost', 'Tie', 'No Result'))
);

---------------------------------------------------------------------------------------------------------------

CREATE TABLE batsman_data_odi (
    id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    player_name         VARCHAR2(100) NOT NULL,
    country             VARCHAR2(50),
    time_period         VARCHAR2(30),
    matches             NUMBER CHECK (matches >= 0),
    played              NUMBER,
    not_outs            NUMBER,
    runs                NUMBER,
    highest_score       NUMBER,
    batting_average     NUMBER(5,2),
    balls_faced         NUMBER,
    strike_rate         NUMBER(5,2),
    centuries           NUMBER,
    fifties             NUMBER,
    ducks               NUMBER,
    fours               NUMBER,
    sixes               NUMBER
);

---------------------------------------------------------------------------------------------------------------

CREATE TABLE batsman_data_t20i (
    id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    player_name         VARCHAR2(100) NOT NULL,
    country             VARCHAR2(50),
    time_period         VARCHAR2(30),
    matches             NUMBER CHECK (matches >= 0),
    played              NUMBER,
    not_outs            NUMBER,
    runs                NUMBER,
    highest_score       NUMBER,
    batting_average     VARCHAR2(10), -- includes '-' sometimes
    balls_faced         NUMBER,
    strike_rate         NUMBER(5,2),
    centuries           NUMBER,
    fifties             NUMBER,
    ducks               NUMBER,
    fours               NUMBER,
    sixes               NUMBER
);

--------------------------------------------------------------------------------------------------------------------

CREATE TABLE batsman_data_t20i (
    id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    player_name         VARCHAR2(100) NOT NULL,
    country             VARCHAR2(50),
    time_period         VARCHAR2(30),
    matches             NUMBER CHECK (matches >= 0),
    played              NUMBER,
    not_outs            NUMBER,
    runs                NUMBER,
    highest_score       NUMBER,
    batting_average     VARCHAR2(10), -- includes '-' sometimes
    balls_faced         NUMBER,
    strike_rate         NUMBER(5,2),
    centuries           NUMBER,
    fifties             NUMBER,
    ducks               NUMBER,
    fours               NUMBER,
    sixes               NUMBER
);

---------------------------------------------------------------------------------------------------------------------

CREATE TABLE bowler_data_odi (
    id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    player_name         VARCHAR2(100) NOT NULL,
    country             VARCHAR2(50),
    time_period         VARCHAR2(30),
    matches             NUMBER,
    played              NUMBER,
    overs               NUMBER(5,2),
    maiden_overs        NUMBER,
    runs                NUMBER,
    wickets             NUMBER,
    best_figure         VARCHAR2(10),
    bowling_average     NUMBER(5,2),
    economy_rate        NUMBER(5,2),
    strike_rate         NUMBER(5,2),
    four_wickets        NUMBER,
    five_wickets        NUMBER
);

-------------------------------------------------------------------------------------------------------------------

CREATE TABLE bowler_data_t20i (
    id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    player_name         VARCHAR2(100) NOT NULL,
    country             VARCHAR2(50),
    time_period         VARCHAR2(30),
    matches             NUMBER,
    played              NUMBER,
    overs               NUMBER(5,2),
    maiden_overs        NUMBER,
    runs                NUMBER,
    wickets             NUMBER,
    best_figure         VARCHAR2(10),
    bowling_average     NUMBER(5,2),
    economy_rate        NUMBER(5,2),
    strike_rate         NUMBER(5,2),
    four_wickets        NUMBER,
    five_wickets        NUMBER
);

--------------------------------------------------------------------------------------------------------------------

CREATE TABLE wicketkeeper_data_odi (
    id                    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    player_name           VARCHAR2(100) NOT NULL,
    country               VARCHAR2(50),
    time_period           VARCHAR2(30),
    matches               NUMBER,
    played                NUMBER,
    dismissals            NUMBER,
    catches               NUMBER,
    stumpings             NUMBER,
    maximum_dismissals    NUMBER
);

---------------------------------------------------------------------------------------------------------------------

CREATE TABLE wicketkeeper_data_t20i (
    id                    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    player_name           VARCHAR2(100) NOT NULL,
    country               VARCHAR2(50),
    time_period           VARCHAR2(30),
    matches               NUMBER,
    played                NUMBER,
    dismissals            NUMBER,
    catches               NUMBER,
    stumpings             NUMBER,
    maximum_dismissals    NUMBER
);

----------------------------------------------------------------------------------------------------------------------

CREATE TABLE champion (
    id                    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    year                  NUMBER(4) NOT NULL,
    host                  VARCHAR2(50),
    no_of_team            NUMBER,
    champion              VARCHAR2(50),
    runner_up             VARCHAR2(50),
    player_of_the_series  VARCHAR2(100),
    highest_run_scorer    VARCHAR2(100),
    highest_wicket_taker  VARCHAR2(100)
);


















